language: ruby
script: 'bundle exec rake ci'
rvm:
  - 1.9.3
  - 2.0.0
  - ruby
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: ruby
notifications:
  irc:
    channels:
      - irc.freenode.org#mutant
    on_success: never
    on_failure: change
